server:
  port: ${port:8080}

logging:
  file:
     name: ./logReservation.log

spring:
  application:
    name: Reservations-SpringBoot

  profiles:
    active: DEV

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./reservations;DATABASE_TO_LOWER=TRUE;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE #DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    tomcat:
      testOnBorrow: true

  h2:
    console:
      enabled: true

# Hibernate

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update) 
        ddl-auto: none
        use_second_level_cache: true
        show_sql: true
        format_sql: false

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    check-location: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html

    operationsSorter: method